# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('classroom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='classroom_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('classroom_id', models.ForeignKey(db_column=b'classroom_id', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='descipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descipline_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='descipline_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(db_column=b'course_id', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.course')),
                ('descipline_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.descipline')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('work_load', models.IntegerField()),
                ('descipline_course_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.descipline_course')),
            ],
        ),
        migrations.CreateModel(
            name='faculty_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.ForeignKey(db_column=b'faculty_id', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='lab',
            fields=[
                ('lab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='lab_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('lab_id', models.ForeignKey(db_column=b'lab_id', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.lab')),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=200)),
                ('descipline_course_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.descipline_course')),
            ],
        ),
        migrations.CreateModel(
            name='semester_batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_batches', models.IntegerField()),
                ('semester_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.semester')),
            ],
        ),
        migrations.CreateModel(
            name='semester_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.ForeignKey(db_column=b'classroom_id', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.classroom')),
                ('semester_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.semester')),
            ],
        ),
        migrations.CreateModel(
            name='semester_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.ForeignKey(db_column=b'lab_id', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.lab')),
                ('semester_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.semester')),
            ],
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=200)),
                ('shift_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_code', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=200)),
                ('is_elective', models.BooleanField(default=False)),
                ('descipline_course_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.descipline_course')),
                ('semester_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.semester')),
            ],
        ),
        migrations.CreateModel(
            name='subject_batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=200)),
                ('subject_code', models.ForeignKey(db_column=b'sub_code', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.subject')),
            ],
        ),
        migrations.CreateModel(
            name='subject_no_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_batch', models.IntegerField()),
                ('sub_code', models.ForeignKey(db_column=b'sub_code', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.subject')),
            ],
        ),
        migrations.CreateModel(
            name='subject_scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_load', models.IntegerField()),
                ('sub_theory_class', models.IntegerField()),
                ('sub_practical_class', models.IntegerField()),
                ('sub_code', models.ForeignKey(db_column=b'sub_code', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.subject')),
            ],
        ),
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot_name', models.CharField(max_length=200)),
                ('shift_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.shift')),
            ],
        ),
        migrations.CreateModel(
            name='timeslot_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.BooleanField()),
                ('resource_id', models.IntegerField()),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.day')),
                ('faculty_subject_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.faculty_subject')),
                ('semester_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.semester')),
                ('shift_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.shift')),
                ('timeslot_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='shift_table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.shift'),
        ),
        migrations.AddField(
            model_name='lab_available',
            name='timeslot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.timeslot'),
        ),
        migrations.AddField(
            model_name='faculty_subject',
            name='sub_code',
            field=models.ForeignKey(db_column=b'subject', on_delete=django.db.models.deletion.CASCADE, to='timetable_final.subject'),
        ),
        migrations.AddField(
            model_name='classroom_available',
            name='timeslot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_final.timeslot'),
        ),
    ]
