# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_final', '0002_auto_20180119_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
