# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_final', '0005_auto_20180124_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_scheme',
            name='sub_tutorial_class',
            field=models.IntegerField(default=0),
        ),
    ]
