# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_final', '0007_semester_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom_available',
            name='day_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_final.day'),
        ),
        migrations.AddField(
            model_name='lab_available',
            name='day_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_final.day'),
        ),
    ]
